### ISSUE TITLE
It fails to recognize the device. 

### ISSUE THREAD

**Issue by TaiKamilla** [x64x6a/PyBadUSB#2]
When I run 

> `python2.7linux_checkinfo.py /dev/sdb1` 

I get this

> Failed getting info

If I try to go ahead anyway with

> `python2.7 -m pybadusb --device /dev/sdb --firmware bin/fw.bin --burner bin/BN03V114M.BIN --payload rubberducky/inject.bin`

I get this:

> Getting device..
> Updating device data...
> Failed getting info!

Any advice or Idea?

Im using a compatible device since I manage to make it work on windows (Not with this project).
But I want it to work on Linux!

**Comment by x64x6a** [comment]
Sorry, I haven't maintained this code in awhile.
It looks like either it is not reading data from your device or the check for 'VR' failed:  https://github.com/x64x6a/PyBadUSB/blob/master/lib/pybadusb/phison.py#L77

Could you also verify that you're using the appropriate path to the device?  For the first example you use `/dev/sdb1`, but for the second you use `/dev/sdb`.

Also, could I ask what chipset the device uses?  And is the device still running the default firmware?
